[[env]]
 _.file = "{{ cwd }}/.env"
[[env]]
 _.file = "{{ cwd }}/.envrc"

[tools]
aqua = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:astral-sh/uv" = "latest"
"aqua:cargo-bins/cargo-binstall" = "latest"
"aqua:cli/cli" = "latest"
"aqua:golangci/golangci-lint" = "latest"
"aqua:hadolint/hadolint" = "latest"
"aqua:jdx/usage" = "latest"
"aqua:jesseduffield/lazygit" = "latest"
"aqua:joerdav/xc" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:sigstore/cosign" = "latest"
"aqua:starship/starship" = "latest"
"aqua:tree-sitter/tree-sitter" = "latest"
"aqua:x-motemen/ghq" = "latest"
bun = "1.3.3"
"cargo:eza" = "latest"
deno = "latest"
"github:neovim/neovim" = "nightly"
go = "1.25"
"go:github.com/babarot/gomi" = "latest"
node = "lts"
"npm:markdownlint-cli2" = "latest"
"npm:mcp-hub" = "latest"
rust = "1.91.1"
zig = "0.15.2"

[settings]
exec_auto_install = false
experimental = true
idiomatic_version_file_enable_tools = ["node"]

[settings.npm]
bun = true
